{
    "CreateLinks": [],
    "OnFailure": "/MDKApp/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/MDKApp/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "createdAt": "#Control:createdAt/#Value",
        "createdBy": "#Control:createdBy/#Value",
        "modifiedAt": "#Control:modifiedAt/#Value",
        "modifiedBy": "#Control:modifiedBy/#Value"
    },
    "Target": {
        "EntitySet": "SrvAuthors",
        "Service": "/MDKApp/Services/service1.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}